import { getAllProjectSlugs, getProjectPageDetails, ProjectFrontmatter, GalleryItem } from '@/lib/projects';
import Link from 'next/link';
import Image from 'next/image';
import ProjectGallery from '@/components/ProjectGallery';

type ProjectPageData = {
    slug: string;
    contentHtml: string;
    gallery: GalleryItem[];
} & ProjectFrontmatter;

export async function generateStaticParams() {
    const paths = getAllProjectSlugs();
    return paths;
}

export default async function ProjectPage({ params: routeParams }: { params: { slug: string[] } }) {
    const { slug: slugArray } = await routeParams;
    const projectData = await getProjectPageDetails(slugArray) as ProjectPageData;

    return (
        <main className="p-4 sm:p-8 bg-gray-900 text-white min-h-screen">
            {/* Increased max-width from max-w-3xl to max-w-4xl */}
            <div className="max-w-4xl mx-auto">
                <Link href="/projects" className="text-cyan-400 hover:underline mb-8 inline-block text-sm">
                    ← Back to All Projects
                </Link>

                {/* Adjusted prose class for larger base text, e.g., from lg:prose-xl to lg:prose-2xl if available, or rely on individual heading overrides */}
                {/* For this example, I'll adjust individual elements and keep prose-xl as a base for the main text body */}
                <article className="prose prose-invert lg:prose-xl max-w-none">
                    {/* Increased Title Size */}
                    <h1 className="text-cyan-400 mb-3 !text-5xl md:!text-6xl">{projectData.title}</h1>

                    {/* Increased Specialty & Tags Size and Spacing */}
                    <div className="mb-8 flex flex-wrap items-center gap-x-4 gap-y-2">
                        {projectData.specialty && (
                            // Increased text size from text-xs to text-sm
                            <span className="bg-cyan-700 text-cyan-100 text-sm font-semibold px-3 py-1.5 rounded-full">
                {projectData.specialty}
              </span>
                        )}
                        <div className="flex flex-wrap gap-2">
                            {projectData.tags.map(tag => (
                                // Increased text size from text-xs to text-sm
                                <span key={tag} className="bg-gray-700 text-gray-300 text-sm font-medium px-3 py-1 rounded-full">
                  {tag}
                </span>
                            ))}
                        </div>
                    </div>

                    {/* Layout for Hero Image and Summary */}
                    <div className="flex flex-col md:flex-row md:gap-10 my-10 md:items-center"> {/* Increased gap and margin */}
                        {projectData.heroImage && (
                            <div className="w-full md:w-1/2 lg:w-2/5 flex-shrink-0 mb-6 md:mb-0"> {/* Adjusted width proportions slightly */}
                                <Image
                                    src={projectData.heroImage}
                                    alt={`${projectData.title} cover image`}
                                    width={800} // Increased base width for better quality at larger display
                                    height={600} // Adjusted for a 4:3, can also be 16:9 like 800x450
                                    className="rounded-lg shadow-xl w-full h-auto object-cover"
                                    priority
                                />
                            </div>
                        )}

                        {projectData.summary && (
                            <div className={`leading-relaxed ${projectData.heroImage ? 'md:w-1/2 lg:w-3/5' : 'w-full'}`}> {/* Adjusted width proportions */}
                                {/* Increased Summary Header Size */}
                                <h3 className="text-3xl font-semibold text-cyan-400 mb-3 !mt-0">
                                    Summary
                                </h3>
                                {/* Increased Summary Text Size */}
                                <p className="text-lg md:text-xl text-gray-300 m-0">
                                    {projectData.summary}
                                </p>
                            </div>
                        )}
                    </div>

                    {/* Increased Details Header Size */}
                    <h3 className="text-3xl font-semibold text-cyan-400 mb-4 !mt-10">
                        Details
                    </h3>
                    {/* The div below will inherit its base font size from 'prose-xl' (approx 20px).
              If you want larger body text, you could try 'lg:prose-2xl' on the <article> tag,
              or add specific text size classes to paragraphs generated by the Markdown if needed.
              For now, prose-xl should provide good readability.
          */}
                    <div dangerouslySetInnerHTML={{ __html: projectData.contentHtml }} />

                    {projectData.gallery && projectData.gallery.length > 0 && (
                        <section className="mt-16"> {/* Increased top margin */}
                            {/* Increased Gallery Header Size */}
                            <h2 className="text-3xl font-semibold text-cyan-400 mb-8 !mt-0">
                                Gallery
                            </h2>
                            <ProjectGallery gallery={projectData.gallery} />
                        </section>
                    )}
                </article>
            </div>
        </main>
    );
}